# Generated by Django 4.0.6 on 2022-08-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=200)),
                ('Product_Catogary', models.CharField(max_length=200)),
                ('Product_Discription', models.CharField(max_length=1000)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Image', models.ImageField(upload_to='product_image')),
            ],
        ),
    ]
